In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [2]:
dataset = pd.read_csv(r'C:\Users\komalakshitha\Desktop\car.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 6].values


In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
labelencoder_X = LabelEncoder()
X[:,1] = labelencoder_X.fit_transform(X[:,1])
labelencoder_X = LabelEncoder()
X[:,2] = labelencoder_X.fit_transform(X[:,2])
labelencoder_X = LabelEncoder()
X[:,3] = labelencoder_X.fit_transform(X[:,3])
labelencoder_X = LabelEncoder()
X[:,4] = labelencoder_X.fit_transform(X[:,4])
labelencoder_X = LabelEncoder()
X[:,5] = labelencoder_X.fit_transform(X[:,5])
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray()

c:\users\komalakshitha\miniconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [5]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [6]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()    
classifier.fit(X_train, y_train,)


GaussianNB(priors=None, var_smoothing=1e-09)

In [7]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [8]:

#Predicting the accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print ("confusion matrix is")
print (cm)
print ("accuracy is")
print (accuracy)

confusion matrix is
[[121  28   0   6]
 [  0  24   0   5]
 [101   1 378   0]
 [  0   0   0  28]]
accuracy is
0.796242774566474
