In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [2]:
dataset = pd.read_csv(r'C:\Users\komalakshitha\Desktop\car.csv')
X = dataset.iloc[:,[0,3,5]].values
y = dataset.iloc[:, 6].values

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
labelencoder_X = LabelEncoder()
X[:,1] = labelencoder_X.fit_transform(X[:,1])
labelencoder_X = LabelEncoder()
X[:,2] = labelencoder_X.fit_transform(X[:,2])
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 0)

In [6]:
from sklearn import svm
classifier = svm.SVC(kernel='rbf')    
classifier.fit(X_train, y_train)

c:\users\komalakshitha\miniconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [7]:
y_pred = classifier.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [9]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print ("confusion matrix is")
print (cm)
print ("accuracy is")
print (accuracy)

confusion matrix is
[[136   0  57   0]
 [ 32   0   0   0]
 [ 46   0 553   0]
 [ 40   0   0   0]]
accuracy is
0.7974537037037037
